services:
  db:
    image: postgres:16
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env

  backend:
    restart: unless-stopped
    container_name: django-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/api
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  
  frontend:
    restart: unless-stopped
    container_name: nextjs-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: npm run dev
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
  
volumes:
  postgres_data: