site_name: Docs - Rei e Rainha da Derivada
repo_url: https://github.com/UnB-Coding/rei-da-derivada
repo_name: RRDD

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigations.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
  language: pt-BR

  markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - attr_list

    

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: default
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: default
      accent: yellow